ImagePrint/Areas/Admin/Controllers/AdminLoginController.cs
using ImagePrint.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ImagePrint.Areas.Admin.Controllers
{
    public class AdminLoginController : Controller
    {
        private MyImageDBEntities db = new MyImageDBEntities();
        // GET: Admin/AdminLogin
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(Member member)
        {
            string encode = Utility.EncodeMD5(member.PassM);
            member.PassM = encode;

            var result = db.Members.Where(a => a.UserM == member.UserM && a.PassM == member.PassM).SingleOrDefault();
            if (result != null)
            {
                Session["admin"] = member;
                return RedirectToAction("Index", "Members");
            }
            else
            {
                ModelState.AddModelError("", "Login Fail! Wrong username or password");
                return View();
            }
        }

        public ActionResult LogOut()
        {
            Session["admin"] = null;
            return RedirectToAction("Index", "Home", new { area = "" });
        }
    }
}

ImagePrint/Areas/Admin/Views/AdminLogin/Index.cshtml
@model ImagePrint.Models.Member

@{
    ViewBag.Title = "Index";
}

<h2>Admin Login</h2>


@using (Html.BeginForm("Index", "AdminLogin"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="color:white">


        <div class="form-group">
            @Html.LabelFor(model => model.UserM, "Admin Username", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserM, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserM, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PassM, "Admin Password", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.PassM, new { @class = "form-control", @type = "password" })
                @Html.ValidationMessageFor(model => model.PassM, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-outline-light" />
                @Html.ValidationSummary(true, null, new { @class = "alert alert-danger my-notice" })
            </div>
        </div>
    </div>
}