ImagePrint/Areas/Admin/Controllers/CustomersController.cs
using ImagePrint.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ImagePrint.Areas.Admin.Controllers
{
    public class CustomersController : Controller
    {
        private MyImageDBEntities db = new MyImageDBEntities();

        // GET: Admin/Customers
        public ActionResult Index()
        {
            if (!IsAdminLoggedIn())
                return RedirectToAction("Index", "AdminLogin");

            return View(db.Customers.ToList());
        }

        // GET: Admin/Customers/Details/5
        public ActionResult Details(decimal id)
        {
            if (!IsAdminLoggedIn())
                return RedirectToAction("Index", "AdminLogin");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: Admin/Customers/Create
        public ActionResult Create()
        {
            if (!IsAdminLoggedIn())
                return RedirectToAction("Index", "AdminLogin");

            return View();
        }

        // POST: Admin/Customers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CusId,F_name,L_name,Dob,Gender,Phone_No,Address,UserCus,PassCus")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                string encode = Utility.EncodeMD5(customer.PassCus);
                customer.PassCus = encode;

                db.Customers.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customer);
        }

        // GET: Admin/Customers/Edit/5
        public ActionResult Edit(decimal id)
        {
            if (!IsAdminLoggedIn())
                return RedirectToAction("Index", "AdminLogin");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Admin/Customers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CusId,F_name,L_name,Dob,Gender,Phone_No,Address,UserCus,PassCus")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                string encode = Utility.EncodeMD5(customer.PassCus);
                customer.PassCus = encode;

                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: Admin/Customers/Delete/5
        public ActionResult Delete(decimal id)
        {
            if (!IsAdminLoggedIn())
                return RedirectToAction("Index", "AdminLogin");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Admin/Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(decimal id)
        {
            if (!IsAdminLoggedIn())
                return RedirectToAction("Index", "AdminLogin");

            Customer customer = db.Customers.Find(id);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool IsAdminLoggedIn()
        {
            if (Session["admin"] == null)
                return false;
            return true;
        }
    }
}

ImagePrint/Controllers/LoginCustomerController.cs
using ImagePrint.Areas;
using ImagePrint.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ImagePrint.Controllers
{
    public class LoginCustomerController : Controller
    {
        private MyImageDBEntities db = new MyImageDBEntities();
        public ActionResult SignUp()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SignUp(Customer customer)
        {
            customer.PassCus = Utility.EncodeMD5(customer.PassCus);
            db.Customers.Add(customer);
            db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(Customer customer)
        {
            customer.PassCus = Utility.EncodeMD5(customer.PassCus);
            var rs = db.Customers.Where(x => x.UserCus == customer.UserCus && x.PassCus == customer.PassCus).SingleOrDefault();
            if (rs != null)
            {
                Session["user"] = rs;
                return RedirectToAction("UploadImage", "Print");
            }
            else
            {
                ModelState.AddModelError("", "Username or Password Incorrect !");
            }
            return View(customer);
        }
        public ActionResult LogOut()
        {
            Session["user"] = null;
            return RedirectToAction("Index", "Home");
        }
    }
}

ImagePrint/Areas/Admin/Views/Shared/_Layout.cshtml
@using ImagePrint.Models;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar fixed-top navbar-expand-md navbar-dark bg-dark">
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a href='@Url.Action("Index","Home", new { area = "" })'>
            <span class="btn my-btn btn-xs btn-outline-primary">
                <b>To Homepage !</b>
            </span>
        </a>
        <a href='@Url.Action("Login","LoginCustomer", new { area = "" })'>
            <span class="btn my-btn btn-xs btn-outline-info">
                <b>Print Image</b>
            </span>
        </a>
        <div class="navbar-collapse collapse mr-auto">
            @if (Session["admin"] != null)
            {
                Member admin = (Member)Session["admin"];
                <ul class="nav navbar-nav sign-in-out ml-md-auto m-2">
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" href="#">
                            <i class="fa-unlock-alt" aria-hidden="true">Wellcome,<span style="color:aqua;">@admin.UserM</span> </i>
                        </a>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="@Url.Action("Index", "Customers")"> Manage Customers Info</a></li>
                    <li class="nav-item"><a class="nav-link text-white bg-danger text-decoration-none" href='@Url.Action("LogOut","AdminLogin")'>Sign Out</a></li>
                </ul>

            }
            else
            {
                <ul class="nav navbar-nav sign-in-out ml-md-auto m-2">
                    <li class="nav-item"><a class="nav-link" href='@Url.Action("Index","AdminLogin")'>Admin Sign In</a></li>
                </ul>
            }
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Image Print Site</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>